packages:
  - name: app
    type: go
    srcs:
      - "**/*.go"
      - "go.mod"
      - "go.sum"
    deps:
      - components/common-go:lib
      - components/usage:lib
    env:
      - CGO_ENABLED=0
      - GOOS=linux
    config:
      packaging: app
      buildCommand: ["go", "build", "-trimpath", "-ldflags", "-buildid= -w -s -X 'github.com/gitpod-io/gitpod/usage/cmd.Version=commit-${__git_commit}'"]

  - name: lib
    type: go
    deps:
      - components/common-go:lib
      - components/usage:lib
    srcs:
      - "**/*.go"
      - "go.mod"
      - "go.sum"
    config:
      packaging: library
      dontTest: true

  - name: docker
    type: docker
    deps:
      - :app
    argdeps:
      - imageRepoBase
    config:
      buildArgs:
        VERSION: ${version}
      dockerfile: leeway.Dockerfile
      metadata:
        helm-component: easy
      image:
        - ${imageRepoBase}/easy:${version}
        - ${imageRepoBase}/easy:commit-${__git_commit}
