name: public-api-compatibility
on: pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: bufbuild/buf-setup-action@v1
      - uses: bufbuild/buf-lint-action@v1
        with:
          input: "components/public-api"
      - uses: bufbuild/buf-breaking-action@v1
        with:
          input: "components/public-api"
          # We compare against the target branch of the Pull Request, normally main
          # Note that we only apply breaking detection to the public-api component.
<<<<<<< HEAD
          against: "https://github.com/${GITHUB_REPOSITORY}.git#branch=${GITHUB_BASE_REF},subdir=components/public-api"
=======
          against: "https://github.com/${GITHUB_REPOSITORY}.git#branch=${GITHUB_BASE_REF},ref=HEAD~1,subdir=components/public-api"
>>>>>>> 7db44b933 ([actions] Buf breaking)
